name: BIN_Gits
on: [push, pull_request]
jobs:
  build:
    name: BIN_Github
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 500
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 3
    env:
        NUM_JOBS: 500
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        sudo apt update
